%global tl_name cmap
%global tl_revision 77682

Name:		texlive-%{tl_name}
Epoch:		1
Version:	1.0j
Release:	%{tl_revision}.1
Summary:	Make PDF files searchable and copyable
Group:		Publishing
URL:		https://www.ctan.org/tex-archive/macros/latex/contrib/cmap
License:	lppl
Source0:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/cmap.r%{tl_revision}.tar.xz
Source1:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/cmap.doc.r%{tl_revision}.tar.xz
BuildArch:	noarch
BuildSystem:	texlive
BuildRequires:	texlive-tlpkg
%texlive_base_requires
Provides:	texlive(%{tl_name}) = %{tl_revision}

%description
The cmap package provides character map tables, which make PDF files
generated by pdfLaTeX both searchable and copy-able in acrobat reader
and other compliant PDF viewers. Encodings supported are OT1, OT6, T1,
T2A, T2B, T2C and T5, together with LAE (Arabic), LFE (Farsi) and LGR
(Greek) and a variant OT1tt for cmtt-like fonts. The package's main
limitation currently is the inability to work with virtual fonts,
because of limitations of pdfTeX. This restriction may be resolved in a
future version of pdfTeX.

